### ISSUE TITLE
Purpose of this plugin?

### ISSUE THREAD

**Issue by Mario-M** [dz0ny/LiveReload-sublimetext2#109]
Can someone help me understand the purpose of this plugin? Been trying to find an answer everywhere but to no avail. Hence this last resort.

I have LiveReload server installed, Chrome browser extension installed, and when I save my html/css I see the LiveReload magic happen in my browser. This is without this plugin installed.

After installing this plugin, I get the exact same behaviour. I'm just not sure exactly what type of functionality this plugin provides but I'm sure there IS something.. and I'd like to know about it ;)

Cheers.

**Comment by daslicht** [comment]
This plugin is used when not having installed LiveReload on the server.
How did you install Livereload on the server please ?

**Comment by Mario-M** [comment]
server - http://livereload.com/
extension: https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en
